spring.application.name=NEOAPP

#Configuracion de la base de datos
#h2 Configuracion BASE - Conexion a la base de datos y usuario y contraseña de administrador de pruebas y tomar la primera linea de codigo y pegar en la pagina de la bd
spring.datasource.url= jdbc:h2:mem: _app_bd
spring.datasource.username= sa
spring.datasource.password=

#h2 Habilitadores consola - lo que gestiona en base de datos
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#Habilitar JPA - crea la base de datos desde java
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true